version: 'latest'
services:
  sys_control:
    image: sys_control
    container_name: mysyscontrol
    build:
      context: ./sys_control
      dockerfile: sys_control/Dockerfile-sysControl
    ports:
      - "11451:11451"
    expose:
      - "11451"
    depends_on:
      - redis
      - user_system
    networks:
      - back_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /opt/avatar:/opt/avatar

  user_system:
    image: user_system
    container_name: myusersystem
    build:
      context: ./user_system
      dockerfile: user_system/Dockerfile-userSystem
    ports:
      - "8088:8088"
    expose:
      - "8088"
    depends_on:
      - redis
    networks:
      - back_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: "myredis"
    container_name: myredis
    networks:
      - back_network
    ports:
      - "6379:6379"

networks:
  back_network:
    driver: bridge